# -*- coding: utf-8 -*-


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # 初始大小设置
        MainWindow.resize(1296, 792)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.setMinimumSize(QtCore.QSize(800, 600))
        # self.setMaximumSize(QtCore.QSize(1600, 1200))
        # MainWindow.setMaximumSize(QtCore.QSize(1600, 1200))
        # 启动时最大化显示
        # self.setWindowState(QtCore.Qt.WindowState.WindowMaximized)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 110))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 110))
        self.widget.setObjectName("widget")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_17.setSpacing(2)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setMaximumSize(QtCore.QSize(90, 28))
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(240, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 28))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_11.addWidget(self.lineEdit)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_11)
        spacerItem = QtWidgets.QSpacerItem(42, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setMaximumSize(QtCore.QSize(120, 32))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_14.addWidget(self.pushButton)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setMaximumSize(QtCore.QSize(90, 28))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_12.addWidget(self.label_18)
        self.folder_path = QtWidgets.QLineEdit(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folder_path.sizePolicy().hasHeightForWidth())
        self.folder_path.setSizePolicy(sizePolicy)
        self.folder_path.setMinimumSize(QtCore.QSize(240, 0))
        self.folder_path.setMaximumSize(QtCore.QSize(16777215, 28))
        self.folder_path.setObjectName("folder_path")
        self.horizontalLayout_12.addWidget(self.folder_path)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_12)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.pushButton_plot_graph_sum = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_plot_graph_sum.setMaximumSize(QtCore.QSize(120, 32))
        self.pushButton_plot_graph_sum.setObjectName("pushButton_plot_graph_sum")
        self.horizontalLayout_15.addWidget(self.pushButton_plot_graph_sum)
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout_17.addWidget(self.tabWidget)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_17.setWordWrap(False)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_5.addWidget(self.label_17)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout.addWidget(self.lineEdit_4)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_6.addWidget(self.lineEdit_5)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_8.addWidget(self.lineEdit_6)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_9.addWidget(self.lineEdit_2)
        self.toolButton_2 = QtWidgets.QToolButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_2.sizePolicy().hasHeightForWidth())
        self.toolButton_2.setSizePolicy(sizePolicy)
        self.toolButton_2.setMinimumSize(QtCore.QSize(0, 0))
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_9.addWidget(self.toolButton_2)
        self.toolButton = QtWidgets.QToolButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMinimumSize(QtCore.QSize(0, 0))
        self.toolButton.setMaximumSize(QtCore.QSize(16777215, 28))
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_9.addWidget(self.toolButton)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_9.addWidget(self.lineEdit_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_16.addLayout(self.verticalLayout_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_16.addWidget(self.pushButton_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addWidget(self.widget)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(3)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.graph_layout = QtWidgets.QVBoxLayout()
        self.graph_layout.setContentsMargins(2, 2, 2, 2)
        self.graph_layout.setObjectName("graph_layout")
        # 创建并配置 label_picture
        self.label_picture = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)  # 不需要水平拉伸
        sizePolicy.setVerticalStretch(0)    # 不需要垂直拉伸
        sizePolicy.setHeightForWidth(False) # 不使用高度依赖宽度
        self.label_picture.setSizePolicy(sizePolicy)
        self.label_picture.setAutoFillBackground(False)
        self.label_picture.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_picture.setObjectName("label_picture")

        self.graph_layout.addWidget(self.label_picture)
        self.verticalLayout_8.addLayout(self.graph_layout)

        self.horizontalLayout_13.addWidget(self.widget_2)

        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_3)

        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_12 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(65)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(80, 0))
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        spacerItem6 = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.label_16 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_2.addWidget(self.label_16)
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(65)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(80, 0))
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 1)
        self.horizontalLayout_2.setStretch(4, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_14 = QtWidgets.QLabel(self.widget_3)
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_13 = QtWidgets.QLabel(self.widget_3)
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.label_10 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(80, 0))
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        spacerItem7 = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.label_15 = QtWidgets.QLabel(self.widget_3)
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_3.addWidget(self.label_15)
        self.label_11 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(80, 0))
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 1)
        self.horizontalLayout_3.setStretch(4, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.addPeak = QtWidgets.QPushButton(self.widget_3)
        self.addPeak.setObjectName("addPeak")
        self.horizontalLayout_4.addWidget(self.addPeak)
        self.savePeakdata = QtWidgets.QPushButton(self.widget_3)
        self.savePeakdata.setObjectName("savePeakdata")
        self.horizontalLayout_4.addWidget(self.savePeakdata)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.peakResult = QtWidgets.QTabWidget(self.widget_3)
        self.peakResult.setObjectName("peakResult")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.peakData = QtWidgets.QTableWidget(self.tab_2)
        self.peakData.setObjectName("peakData")
        self.peakData.setColumnCount(6)
        self.peakData.setRowCount(9)
        headers = ["Species", "飞行时间", "质量数 (m/z)", "强度", "左边界", "右边界"]
        self.peakData.setHorizontalHeaderLabels(headers)
        item = QtWidgets.QTableWidgetItem()
        self.peakData.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peakData.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peakData.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peakData.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peakData.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peakData.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.peakData.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.peakData.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.peakData.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.peakData.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peakData.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peakData.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peakData.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peakData.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peakData.setHorizontalHeaderItem(5, item)
        self.peakData.horizontalHeader().setCascadingSectionResizes(True)
        self.peakData.horizontalHeader().setDefaultSectionSize(70)
        self.peakData.verticalHeader().setVisible(False)
        self.peakData.verticalHeader().setHighlightSections(True)
        self.verticalLayout_3.addWidget(self.peakData)
        self.peakResult.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.region = QtWidgets.QTableWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.region.sizePolicy().hasHeightForWidth())
        self.region.setSizePolicy(sizePolicy)
        self.region.setMinimumSize(QtCore.QSize(0, 1))
        self.region.setSizeIncrement(QtCore.QSize(1, 1))
        self.region.setBaseSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(11)
        self.region.setFont(font)
        self.region.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.region.setAutoFillBackground(False)
        self.region.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.region.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.region.setAutoScrollMargin(1)
        self.region.setShowGrid(True)
        self.region.setGridStyle(QtCore.Qt.PenStyle.DashDotDotLine)
        self.region.setRowCount(12)
        self.region.setObjectName("region")
        self.region.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.region.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.region.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.region.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.region.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.region.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.region.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.region.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.region.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.region.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.region.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.region.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.region.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.region.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.region.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.region.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.region.setItem(6, 1, item)
        self.region.horizontalHeader().setCascadingSectionResizes(False)
        self.region.horizontalHeader().setDefaultSectionSize(135)
        self.region.horizontalHeader().setHighlightSections(True)
        self.region.horizontalHeader().setMinimumSectionSize(43)
        self.region.horizontalHeader().setSortIndicatorShown(False)
        self.region.horizontalHeader().setStretchLastSection(True)
        self.region.verticalHeader().setVisible(False)
        self.region.verticalHeader().setCascadingSectionResizes(False)
        self.region.verticalHeader().setDefaultSectionSize(30)
        self.region.verticalHeader().setHighlightSections(False)
        self.region.verticalHeader().setMinimumSectionSize(30)
        self.region.verticalHeader().setSortIndicatorShown(False)
        self.region.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.region)
        self.peakResult.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.peakResult)
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_3.setMinimumSize(QtCore.QSize(93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_7.addWidget(self.pushButton_3)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.horizontalLayout_13.addWidget(self.widget_3)
        self.horizontalLayout_13.setStretch(0, 5)
        self.horizontalLayout_13.setStretch(1, 3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.verticalLayout_7.setStretch(0, 3)
        self.verticalLayout_7.setStretch(1, 7)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1296, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label.setBuddy(self.lineEdit)
        self.label_18.setBuddy(self.lineEdit)
        self.label_2.setBuddy(self.lineEdit_2)
        self.label_3.setBuddy(self.lineEdit_3)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.peakResult.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 调整窗口大小和布局
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setWindowTitle("BL03U Mass Spectrum Tool")
        
        self.pushButton.setToolTip("查看单个质谱图")
        self.pushButton_plot_graph_sum.setToolTip("查看文件夹中所有质谱图的累加图")
        self.pushButton_4.setToolTip("自动检测质谱图中的峰值")
        self.lineEdit.setToolTip("输入单个文件的路径")
        self.folder_path.setToolTip("输入包含多个文件的文件夹路径")

        # 添加复选框
        self.checkBox_show_gaussian = QtWidgets.QCheckBox(MainWindow)
        self.checkBox_show_gaussian.setObjectName("checkBox_show_gaussian")
        self.checkBox_show_gaussian.setText("显示高斯拟合图")
        self.verticalLayout_9.addWidget(self.checkBox_show_gaussian)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "文件地址："))
        self.lineEdit.setText(_translate("MainWindow", "tests/fixtures/C6F11O2H/Temp_Scan/12.5eV/C23072508-0000.txt"))
        self.pushButton.setText(_translate("MainWindow", "查看单谱"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "单谱"))
        self.label_18.setText(_translate("MainWindow", "文件夹地址："))
        self.folder_path.setText(_translate("MainWindow", "tests/fixtures/C6F11O2H/Temp_Scan/12.5eV"))
        self.pushButton_plot_graph_sum.setText(_translate("MainWindow", "查看累加谱"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "累加谱"))
        self.label_17.setText(_translate("MainWindow", "质量定标参数："))
        self.label_5.setText(_translate("MainWindow", "A:"))
        self.lineEdit_4.setText(_translate("MainWindow", "3.66334E-07 "))
        self.label_6.setText(_translate("MainWindow", "B:"))
        self.lineEdit_5.setText(_translate("MainWindow", "0.000637719"))
        self.label_7.setText(_translate("MainWindow", "C:"))
        self.lineEdit_6.setText(_translate("MainWindow", "0.272489072"))
        self.label_2.setText(_translate("MainWindow", "飞行时间"))
        self.label_3.setText(_translate("MainWindow", "质量数"))
        self.toolButton_2.setText(_translate("MainWindow", "<-"))
        self.toolButton.setText(_translate("MainWindow", "->"))
        self.pushButton_4.setText(_translate("MainWindow", "自动寻峰"))
        self.label_picture.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "Time："))
        self.label_8.setText(_translate("MainWindow", "peak"))
        self.label_16.setText(_translate("MainWindow", "M/Z："))
        self.label_9.setText(_translate("MainWindow", "M/Z"))
        self.label_14.setText(_translate("MainWindow", "Range"))
        self.label_13.setText(_translate("MainWindow", "Left："))
        self.label_10.setText(_translate("MainWindow", "left"))
        self.label_15.setText(_translate("MainWindow", "Right："))
        self.label_11.setText(_translate("MainWindow", "right"))
        self.addPeak.setText(_translate("MainWindow", "添加峰"))
        self.savePeakdata.setText(_translate("MainWindow", "导出卡峰范围"))
        item = self.peakData.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.peakData.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.peakData.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.peakData.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.peakData.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.peakData.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.peakData.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.peakData.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.peakData.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.peakData.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Species"))
        item = self.peakData.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "飞行时间"))
        item = self.peakData.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "质量数 (m/z)"))
        item = self.peakData.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "强度"))
        item = self.peakData.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "左边界"))
        item = self.peakData.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "右边界"))
        self.peakResult.setTabText(self.peakResult.indexOf(self.tab_2), _translate("MainWindow", "卡峰范围"))
        item = self.region.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Peak"))
        item = self.region.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "M/Z"))
        __sortingEnabled = self.region.isSortingEnabled()
        self.region.setSortingEnabled(False)
        item = self.region.item(0, 0)
        item.setText(_translate("MainWindow", "6127.755"))
        item = self.region.item(0, 1)
        item.setText(_translate("MainWindow", "18.01002"))
        item = self.region.item(1, 0)
        item.setText(_translate("MainWindow", "8457.441"))
        item = self.region.item(1, 1)
        item.setText(_translate("MainWindow", "31.98983"))
        item = self.region.item(2, 0)
        item.setText(_translate("MainWindow", "10068.66"))
        item = self.region.item(2, 1)
        item.setText(_translate("MainWindow", "43.98983"))
        item = self.region.item(3, 0)
        item.setText(_translate("MainWindow", "14058.12"))
        item = self.region.item(3, 1)
        item.setText(_translate("MainWindow", "81.91294"))
        item = self.region.item(4, 0)
        item.setText(_translate("MainWindow", "14149.07"))
        item = self.region.item(4, 1)
        item.setText(_translate("MainWindow", "82.91359"))
        item = self.region.item(5, 0)
        item.setText(_translate("MainWindow", "14238.99"))
        item = self.region.item(5, 1)
        item.setText(_translate("MainWindow", "83.91096"))
        item = self.region.item(6, 0)
        item.setText(_translate("MainWindow", "14418.0"))
        item = self.region.item(6, 1)
        item.setText(_translate("MainWindow", "85.91006"))
        self.region.setSortingEnabled(__sortingEnabled)
        self.peakResult.setTabText(self.peakResult.indexOf(self.tab), _translate("MainWindow", "质谱定标"))
        self.label_4.setText(_translate("MainWindow", "Y=C+BX+AX^2，R^2"))
        self.pushButton_3.setText(_translate("MainWindow", "计算"))
