normalization:
  light_source: io
  temperature_photon_normalize: true
  temperature_kr_correct: true
  pie_photon_mode: first
  mass_discrimination: 1.0
  kr_calibration_folder: /Users/huangchen/VscodeProject/BL03U_MSTool_clean_repo/BL03U_MassSpectrumTool/tests/fixtures/bl03u_sample/顺-13-二甲基环己烷
    30 torr/温度扫描/14.6-14.8eV/
  kr_calibration_peak_file: ''
  expansion_factors:
    650.0: 1.0
    750.0: 1.0
    800.0: 1.0
    850.0: 1.0
    875.0: 0.999842803004034
    900.0: 1.0
    925.0: 1.0082859976074727
    950.0: 1.0092146084432485
    975.0: 1.0120791750696545
    1000.0: 1.0005354061414384
  selected_elements:
  - H
  - C
  - N
  - O
  - F
  - Cl
  - Br
  - I
  - S
  - P
  - Si
